#pragma once

using namespace ATL;

template <class T>
class CProxy_ICardObjectEvents : public IConnectionPointImpl<T, &__uuidof( _ICardObjectEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
