/* soapH.h
   Generated by gSOAP 2.8.15 from wpsoap.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_serialize_byte(soap, data), soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_serialize_int(soap, data), soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns1__getMainKeyResponse
#define SOAP_TYPE_ns1__getMainKeyResponse (20)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getMainKeyResponse(struct soap*, const char*, int, const ns1__getMainKeyResponse *, const char*);
SOAP_FMAC3 ns1__getMainKeyResponse * SOAP_FMAC4 soap_in_ns1__getMainKeyResponse(struct soap*, const char*, ns1__getMainKeyResponse *, const char*);

#ifndef soap_write_ns1__getMainKeyResponse
#define soap_write_ns1__getMainKeyResponse(soap, data) ( (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:getMainKeyResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__getMainKeyResponse * SOAP_FMAC4 soap_get_ns1__getMainKeyResponse(struct soap*, ns1__getMainKeyResponse *, const char*, const char*);

#ifndef soap_read_ns1__getMainKeyResponse
#define soap_read_ns1__getMainKeyResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__getMainKeyResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 ns1__getMainKeyResponse * SOAP_FMAC2 soap_instantiate_ns1__getMainKeyResponse(struct soap*, int, const char*, const char*, size_t*);

inline ns1__getMainKeyResponse * soap_new_ns1__getMainKeyResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns1__getMainKeyResponse(soap, n, NULL, NULL, NULL); }

inline ns1__getMainKeyResponse * soap_new_req_ns1__getMainKeyResponse(struct soap *soap) { ns1__getMainKeyResponse *_p = soap_instantiate_ns1__getMainKeyResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__getMainKeyResponse * soap_new_set_ns1__getMainKeyResponse(struct soap *soap, char *return_) { ns1__getMainKeyResponse *_p = soap_instantiate_ns1__getMainKeyResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__getMainKeyResponse::return_ = return_; } return _p; }

inline void soap_delete_ns1__getMainKeyResponse(struct soap *soap, ns1__getMainKeyResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getMainKeyResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getMainKey
#define SOAP_TYPE_ns1__getMainKey (19)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getMainKey(struct soap*, const char*, int, const ns1__getMainKey *, const char*);
SOAP_FMAC3 ns1__getMainKey * SOAP_FMAC4 soap_in_ns1__getMainKey(struct soap*, const char*, ns1__getMainKey *, const char*);

#ifndef soap_write_ns1__getMainKey
#define soap_write_ns1__getMainKey(soap, data) ( (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:getMainKey", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__getMainKey * SOAP_FMAC4 soap_get_ns1__getMainKey(struct soap*, ns1__getMainKey *, const char*, const char*);

#ifndef soap_read_ns1__getMainKey
#define soap_read_ns1__getMainKey(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__getMainKey(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 ns1__getMainKey * SOAP_FMAC2 soap_instantiate_ns1__getMainKey(struct soap*, int, const char*, const char*, size_t*);

inline ns1__getMainKey * soap_new_ns1__getMainKey(struct soap *soap, int n = -1) { return soap_instantiate_ns1__getMainKey(soap, n, NULL, NULL, NULL); }

inline ns1__getMainKey * soap_new_req_ns1__getMainKey(struct soap *soap) { ns1__getMainKey *_p = soap_instantiate_ns1__getMainKey(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__getMainKey * soap_new_set_ns1__getMainKey(struct soap *soap) { ns1__getMainKey *_p = soap_instantiate_ns1__getMainKey(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline void soap_delete_ns1__getMainKey(struct soap *soap, ns1__getMainKey *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getMainKey(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getCardTypeRulesResponse
#define SOAP_TYPE_ns1__getCardTypeRulesResponse (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getCardTypeRulesResponse(struct soap*, const char*, int, const ns1__getCardTypeRulesResponse *, const char*);
SOAP_FMAC3 ns1__getCardTypeRulesResponse * SOAP_FMAC4 soap_in_ns1__getCardTypeRulesResponse(struct soap*, const char*, ns1__getCardTypeRulesResponse *, const char*);

#ifndef soap_write_ns1__getCardTypeRulesResponse
#define soap_write_ns1__getCardTypeRulesResponse(soap, data) ( (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:getCardTypeRulesResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__getCardTypeRulesResponse * SOAP_FMAC4 soap_get_ns1__getCardTypeRulesResponse(struct soap*, ns1__getCardTypeRulesResponse *, const char*, const char*);

#ifndef soap_read_ns1__getCardTypeRulesResponse
#define soap_read_ns1__getCardTypeRulesResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__getCardTypeRulesResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 ns1__getCardTypeRulesResponse * SOAP_FMAC2 soap_instantiate_ns1__getCardTypeRulesResponse(struct soap*, int, const char*, const char*, size_t*);

inline ns1__getCardTypeRulesResponse * soap_new_ns1__getCardTypeRulesResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns1__getCardTypeRulesResponse(soap, n, NULL, NULL, NULL); }

inline ns1__getCardTypeRulesResponse * soap_new_req_ns1__getCardTypeRulesResponse(struct soap *soap) { ns1__getCardTypeRulesResponse *_p = soap_instantiate_ns1__getCardTypeRulesResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__getCardTypeRulesResponse * soap_new_set_ns1__getCardTypeRulesResponse(struct soap *soap, char *return_) { ns1__getCardTypeRulesResponse *_p = soap_instantiate_ns1__getCardTypeRulesResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__getCardTypeRulesResponse::return_ = return_; } return _p; }

inline void soap_delete_ns1__getCardTypeRulesResponse(struct soap *soap, ns1__getCardTypeRulesResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getCardTypeRulesResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__getCardTypeRules
#define SOAP_TYPE_ns1__getCardTypeRules (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__getCardTypeRules(struct soap*, const char*, int, const ns1__getCardTypeRules *, const char*);
SOAP_FMAC3 ns1__getCardTypeRules * SOAP_FMAC4 soap_in_ns1__getCardTypeRules(struct soap*, const char*, ns1__getCardTypeRules *, const char*);

#ifndef soap_write_ns1__getCardTypeRules
#define soap_write_ns1__getCardTypeRules(soap, data) ( (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:getCardTypeRules", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__getCardTypeRules * SOAP_FMAC4 soap_get_ns1__getCardTypeRules(struct soap*, ns1__getCardTypeRules *, const char*, const char*);

#ifndef soap_read_ns1__getCardTypeRules
#define soap_read_ns1__getCardTypeRules(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__getCardTypeRules(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 ns1__getCardTypeRules * SOAP_FMAC2 soap_instantiate_ns1__getCardTypeRules(struct soap*, int, const char*, const char*, size_t*);

inline ns1__getCardTypeRules * soap_new_ns1__getCardTypeRules(struct soap *soap, int n = -1) { return soap_instantiate_ns1__getCardTypeRules(soap, n, NULL, NULL, NULL); }

inline ns1__getCardTypeRules * soap_new_req_ns1__getCardTypeRules(struct soap *soap) { ns1__getCardTypeRules *_p = soap_instantiate_ns1__getCardTypeRules(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__getCardTypeRules * soap_new_set_ns1__getCardTypeRules(struct soap *soap) { ns1__getCardTypeRules *_p = soap_instantiate_ns1__getCardTypeRules(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline void soap_delete_ns1__getCardTypeRules(struct soap *soap, ns1__getCardTypeRules *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__getCardTypeRules(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__storeCardResponse
#define SOAP_TYPE_ns1__storeCardResponse (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__storeCardResponse(struct soap*, const char*, int, const ns1__storeCardResponse *, const char*);
SOAP_FMAC3 ns1__storeCardResponse * SOAP_FMAC4 soap_in_ns1__storeCardResponse(struct soap*, const char*, ns1__storeCardResponse *, const char*);

#ifndef soap_write_ns1__storeCardResponse
#define soap_write_ns1__storeCardResponse(soap, data) ( (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:storeCardResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__storeCardResponse * SOAP_FMAC4 soap_get_ns1__storeCardResponse(struct soap*, ns1__storeCardResponse *, const char*, const char*);

#ifndef soap_read_ns1__storeCardResponse
#define soap_read_ns1__storeCardResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__storeCardResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 ns1__storeCardResponse * SOAP_FMAC2 soap_instantiate_ns1__storeCardResponse(struct soap*, int, const char*, const char*, size_t*);

inline ns1__storeCardResponse * soap_new_ns1__storeCardResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns1__storeCardResponse(soap, n, NULL, NULL, NULL); }

inline ns1__storeCardResponse * soap_new_req_ns1__storeCardResponse(struct soap *soap) { ns1__storeCardResponse *_p = soap_instantiate_ns1__storeCardResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__storeCardResponse * soap_new_set_ns1__storeCardResponse(struct soap *soap, char *return_) { ns1__storeCardResponse *_p = soap_instantiate_ns1__storeCardResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__storeCardResponse::return_ = return_; } return _p; }

inline void soap_delete_ns1__storeCardResponse(struct soap *soap, ns1__storeCardResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__storeCardResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__storeCard
#define SOAP_TYPE_ns1__storeCard (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__storeCard(struct soap*, const char*, int, const ns1__storeCard *, const char*);
SOAP_FMAC3 ns1__storeCard * SOAP_FMAC4 soap_in_ns1__storeCard(struct soap*, const char*, ns1__storeCard *, const char*);

#ifndef soap_write_ns1__storeCard
#define soap_write_ns1__storeCard(soap, data) ( (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:storeCard", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__storeCard * SOAP_FMAC4 soap_get_ns1__storeCard(struct soap*, ns1__storeCard *, const char*, const char*);

#ifndef soap_read_ns1__storeCard
#define soap_read_ns1__storeCard(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__storeCard(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 ns1__storeCard * SOAP_FMAC2 soap_instantiate_ns1__storeCard(struct soap*, int, const char*, const char*, size_t*);

inline ns1__storeCard * soap_new_ns1__storeCard(struct soap *soap, int n = -1) { return soap_instantiate_ns1__storeCard(soap, n, NULL, NULL, NULL); }

inline ns1__storeCard * soap_new_req_ns1__storeCard(struct soap *soap) { ns1__storeCard *_p = soap_instantiate_ns1__storeCard(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__storeCard * soap_new_set_ns1__storeCard(struct soap *soap, char *arg0) { ns1__storeCard *_p = soap_instantiate_ns1__storeCard(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__storeCard::arg0 = arg0; } return _p; }

inline void soap_delete_ns1__storeCard(struct soap *soap, ns1__storeCard *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__storeCard(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__generatePasswordResponse
#define SOAP_TYPE_ns1__generatePasswordResponse (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__generatePasswordResponse(struct soap*, const char*, int, const ns1__generatePasswordResponse *, const char*);
SOAP_FMAC3 ns1__generatePasswordResponse * SOAP_FMAC4 soap_in_ns1__generatePasswordResponse(struct soap*, const char*, ns1__generatePasswordResponse *, const char*);

#ifndef soap_write_ns1__generatePasswordResponse
#define soap_write_ns1__generatePasswordResponse(soap, data) ( (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:generatePasswordResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__generatePasswordResponse * SOAP_FMAC4 soap_get_ns1__generatePasswordResponse(struct soap*, ns1__generatePasswordResponse *, const char*, const char*);

#ifndef soap_read_ns1__generatePasswordResponse
#define soap_read_ns1__generatePasswordResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__generatePasswordResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 ns1__generatePasswordResponse * SOAP_FMAC2 soap_instantiate_ns1__generatePasswordResponse(struct soap*, int, const char*, const char*, size_t*);

inline ns1__generatePasswordResponse * soap_new_ns1__generatePasswordResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns1__generatePasswordResponse(soap, n, NULL, NULL, NULL); }

inline ns1__generatePasswordResponse * soap_new_req_ns1__generatePasswordResponse(struct soap *soap) { ns1__generatePasswordResponse *_p = soap_instantiate_ns1__generatePasswordResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__generatePasswordResponse * soap_new_set_ns1__generatePasswordResponse(struct soap *soap, char *return_) { ns1__generatePasswordResponse *_p = soap_instantiate_ns1__generatePasswordResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__generatePasswordResponse::return_ = return_; } return _p; }

inline void soap_delete_ns1__generatePasswordResponse(struct soap *soap, ns1__generatePasswordResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__generatePasswordResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__generatePassword
#define SOAP_TYPE_ns1__generatePassword (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__generatePassword(struct soap*, const char*, int, const ns1__generatePassword *, const char*);
SOAP_FMAC3 ns1__generatePassword * SOAP_FMAC4 soap_in_ns1__generatePassword(struct soap*, const char*, ns1__generatePassword *, const char*);

#ifndef soap_write_ns1__generatePassword
#define soap_write_ns1__generatePassword(soap, data) ( (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:generatePassword", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__generatePassword * SOAP_FMAC4 soap_get_ns1__generatePassword(struct soap*, ns1__generatePassword *, const char*, const char*);

#ifndef soap_read_ns1__generatePassword
#define soap_read_ns1__generatePassword(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__generatePassword(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 ns1__generatePassword * SOAP_FMAC2 soap_instantiate_ns1__generatePassword(struct soap*, int, const char*, const char*, size_t*);

inline ns1__generatePassword * soap_new_ns1__generatePassword(struct soap *soap, int n = -1) { return soap_instantiate_ns1__generatePassword(soap, n, NULL, NULL, NULL); }

inline ns1__generatePassword * soap_new_req_ns1__generatePassword(struct soap *soap) { ns1__generatePassword *_p = soap_instantiate_ns1__generatePassword(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__generatePassword * soap_new_set_ns1__generatePassword(struct soap *soap) { ns1__generatePassword *_p = soap_instantiate_ns1__generatePassword(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline void soap_delete_ns1__generatePassword(struct soap *soap, ns1__generatePassword *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__generatePassword(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__generatePsamCardNoResponse
#define SOAP_TYPE_ns1__generatePsamCardNoResponse (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__generatePsamCardNoResponse(struct soap*, const char*, int, const ns1__generatePsamCardNoResponse *, const char*);
SOAP_FMAC3 ns1__generatePsamCardNoResponse * SOAP_FMAC4 soap_in_ns1__generatePsamCardNoResponse(struct soap*, const char*, ns1__generatePsamCardNoResponse *, const char*);

#ifndef soap_write_ns1__generatePsamCardNoResponse
#define soap_write_ns1__generatePsamCardNoResponse(soap, data) ( (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:generatePsamCardNoResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__generatePsamCardNoResponse * SOAP_FMAC4 soap_get_ns1__generatePsamCardNoResponse(struct soap*, ns1__generatePsamCardNoResponse *, const char*, const char*);

#ifndef soap_read_ns1__generatePsamCardNoResponse
#define soap_read_ns1__generatePsamCardNoResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__generatePsamCardNoResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 ns1__generatePsamCardNoResponse * SOAP_FMAC2 soap_instantiate_ns1__generatePsamCardNoResponse(struct soap*, int, const char*, const char*, size_t*);

inline ns1__generatePsamCardNoResponse * soap_new_ns1__generatePsamCardNoResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns1__generatePsamCardNoResponse(soap, n, NULL, NULL, NULL); }

inline ns1__generatePsamCardNoResponse * soap_new_req_ns1__generatePsamCardNoResponse(struct soap *soap) { ns1__generatePsamCardNoResponse *_p = soap_instantiate_ns1__generatePsamCardNoResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__generatePsamCardNoResponse * soap_new_set_ns1__generatePsamCardNoResponse(struct soap *soap, char *return_) { ns1__generatePsamCardNoResponse *_p = soap_instantiate_ns1__generatePsamCardNoResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__generatePsamCardNoResponse::return_ = return_; } return _p; }

inline void soap_delete_ns1__generatePsamCardNoResponse(struct soap *soap, ns1__generatePsamCardNoResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__generatePsamCardNoResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__generatePsamCardNo
#define SOAP_TYPE_ns1__generatePsamCardNo (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__generatePsamCardNo(struct soap*, const char*, int, const ns1__generatePsamCardNo *, const char*);
SOAP_FMAC3 ns1__generatePsamCardNo * SOAP_FMAC4 soap_in_ns1__generatePsamCardNo(struct soap*, const char*, ns1__generatePsamCardNo *, const char*);

#ifndef soap_write_ns1__generatePsamCardNo
#define soap_write_ns1__generatePsamCardNo(soap, data) ( (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:generatePsamCardNo", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__generatePsamCardNo * SOAP_FMAC4 soap_get_ns1__generatePsamCardNo(struct soap*, ns1__generatePsamCardNo *, const char*, const char*);

#ifndef soap_read_ns1__generatePsamCardNo
#define soap_read_ns1__generatePsamCardNo(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__generatePsamCardNo(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 ns1__generatePsamCardNo * SOAP_FMAC2 soap_instantiate_ns1__generatePsamCardNo(struct soap*, int, const char*, const char*, size_t*);

inline ns1__generatePsamCardNo * soap_new_ns1__generatePsamCardNo(struct soap *soap, int n = -1) { return soap_instantiate_ns1__generatePsamCardNo(soap, n, NULL, NULL, NULL); }

inline ns1__generatePsamCardNo * soap_new_req_ns1__generatePsamCardNo(struct soap *soap) { ns1__generatePsamCardNo *_p = soap_instantiate_ns1__generatePsamCardNo(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__generatePsamCardNo * soap_new_set_ns1__generatePsamCardNo(struct soap *soap) { ns1__generatePsamCardNo *_p = soap_instantiate_ns1__generatePsamCardNo(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline void soap_delete_ns1__generatePsamCardNo(struct soap *soap, ns1__generatePsamCardNo *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__generatePsamCardNo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__storePsamCardResponse
#define SOAP_TYPE_ns1__storePsamCardResponse (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__storePsamCardResponse(struct soap*, const char*, int, const ns1__storePsamCardResponse *, const char*);
SOAP_FMAC3 ns1__storePsamCardResponse * SOAP_FMAC4 soap_in_ns1__storePsamCardResponse(struct soap*, const char*, ns1__storePsamCardResponse *, const char*);

#ifndef soap_write_ns1__storePsamCardResponse
#define soap_write_ns1__storePsamCardResponse(soap, data) ( (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:storePsamCardResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__storePsamCardResponse * SOAP_FMAC4 soap_get_ns1__storePsamCardResponse(struct soap*, ns1__storePsamCardResponse *, const char*, const char*);

#ifndef soap_read_ns1__storePsamCardResponse
#define soap_read_ns1__storePsamCardResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__storePsamCardResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 ns1__storePsamCardResponse * SOAP_FMAC2 soap_instantiate_ns1__storePsamCardResponse(struct soap*, int, const char*, const char*, size_t*);

inline ns1__storePsamCardResponse * soap_new_ns1__storePsamCardResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns1__storePsamCardResponse(soap, n, NULL, NULL, NULL); }

inline ns1__storePsamCardResponse * soap_new_req_ns1__storePsamCardResponse(struct soap *soap) { ns1__storePsamCardResponse *_p = soap_instantiate_ns1__storePsamCardResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__storePsamCardResponse * soap_new_set_ns1__storePsamCardResponse(struct soap *soap, char *return_) { ns1__storePsamCardResponse *_p = soap_instantiate_ns1__storePsamCardResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__storePsamCardResponse::return_ = return_; } return _p; }

inline void soap_delete_ns1__storePsamCardResponse(struct soap *soap, ns1__storePsamCardResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__storePsamCardResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__storePsamCard
#define SOAP_TYPE_ns1__storePsamCard (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__storePsamCard(struct soap*, const char*, int, const ns1__storePsamCard *, const char*);
SOAP_FMAC3 ns1__storePsamCard * SOAP_FMAC4 soap_in_ns1__storePsamCard(struct soap*, const char*, ns1__storePsamCard *, const char*);

#ifndef soap_write_ns1__storePsamCard
#define soap_write_ns1__storePsamCard(soap, data) ( (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:storePsamCard", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__storePsamCard * SOAP_FMAC4 soap_get_ns1__storePsamCard(struct soap*, ns1__storePsamCard *, const char*, const char*);

#ifndef soap_read_ns1__storePsamCard
#define soap_read_ns1__storePsamCard(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__storePsamCard(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 ns1__storePsamCard * SOAP_FMAC2 soap_instantiate_ns1__storePsamCard(struct soap*, int, const char*, const char*, size_t*);

inline ns1__storePsamCard * soap_new_ns1__storePsamCard(struct soap *soap, int n = -1) { return soap_instantiate_ns1__storePsamCard(soap, n, NULL, NULL, NULL); }

inline ns1__storePsamCard * soap_new_req_ns1__storePsamCard(struct soap *soap) { ns1__storePsamCard *_p = soap_instantiate_ns1__storePsamCard(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__storePsamCard * soap_new_set_ns1__storePsamCard(struct soap *soap, char *arg0) { ns1__storePsamCard *_p = soap_instantiate_ns1__storePsamCard(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__storePsamCard::arg0 = arg0; } return _p; }

inline void soap_delete_ns1__storePsamCard(struct soap *soap, ns1__storePsamCard *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__storePsamCard(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__verifyUserResponse
#define SOAP_TYPE_ns1__verifyUserResponse (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__verifyUserResponse(struct soap*, const char*, int, const ns1__verifyUserResponse *, const char*);
SOAP_FMAC3 ns1__verifyUserResponse * SOAP_FMAC4 soap_in_ns1__verifyUserResponse(struct soap*, const char*, ns1__verifyUserResponse *, const char*);

#ifndef soap_write_ns1__verifyUserResponse
#define soap_write_ns1__verifyUserResponse(soap, data) ( (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:verifyUserResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__verifyUserResponse * SOAP_FMAC4 soap_get_ns1__verifyUserResponse(struct soap*, ns1__verifyUserResponse *, const char*, const char*);

#ifndef soap_read_ns1__verifyUserResponse
#define soap_read_ns1__verifyUserResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__verifyUserResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 ns1__verifyUserResponse * SOAP_FMAC2 soap_instantiate_ns1__verifyUserResponse(struct soap*, int, const char*, const char*, size_t*);

inline ns1__verifyUserResponse * soap_new_ns1__verifyUserResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns1__verifyUserResponse(soap, n, NULL, NULL, NULL); }

inline ns1__verifyUserResponse * soap_new_req_ns1__verifyUserResponse(struct soap *soap) { ns1__verifyUserResponse *_p = soap_instantiate_ns1__verifyUserResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__verifyUserResponse * soap_new_set_ns1__verifyUserResponse(struct soap *soap, char *return_) { ns1__verifyUserResponse *_p = soap_instantiate_ns1__verifyUserResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__verifyUserResponse::return_ = return_; } return _p; }

inline void soap_delete_ns1__verifyUserResponse(struct soap *soap, ns1__verifyUserResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__verifyUserResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__verifyUser
#define SOAP_TYPE_ns1__verifyUser (7)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__verifyUser(struct soap*, const char*, int, const ns1__verifyUser *, const char*);
SOAP_FMAC3 ns1__verifyUser * SOAP_FMAC4 soap_in_ns1__verifyUser(struct soap*, const char*, ns1__verifyUser *, const char*);

#ifndef soap_write_ns1__verifyUser
#define soap_write_ns1__verifyUser(soap, data) ( (data)->soap_serialize(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:verifyUser", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__verifyUser * SOAP_FMAC4 soap_get_ns1__verifyUser(struct soap*, ns1__verifyUser *, const char*, const char*);

#ifndef soap_read_ns1__verifyUser
#define soap_read_ns1__verifyUser(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__verifyUser(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 ns1__verifyUser * SOAP_FMAC2 soap_instantiate_ns1__verifyUser(struct soap*, int, const char*, const char*, size_t*);

inline ns1__verifyUser * soap_new_ns1__verifyUser(struct soap *soap, int n = -1) { return soap_instantiate_ns1__verifyUser(soap, n, NULL, NULL, NULL); }

inline ns1__verifyUser * soap_new_req_ns1__verifyUser(struct soap *soap) { ns1__verifyUser *_p = soap_instantiate_ns1__verifyUser(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns1__verifyUser * soap_new_set_ns1__verifyUser(struct soap *soap, char *arg0) { ns1__verifyUser *_p = soap_instantiate_ns1__verifyUser(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns1__verifyUser::arg0 = arg0; } return _p; }

inline void soap_delete_ns1__verifyUser(struct soap *soap, ns1__verifyUser *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__verifyUser(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_serialize_SOAP_ENV__Fault(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Fault * soap_new_SOAP_ENV__Fault(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Fault * soap_new_req_SOAP_ENV__Fault(struct soap *soap) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); } return _p; }

inline struct SOAP_ENV__Fault * soap_new_set_SOAP_ENV__Fault(struct soap *soap, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); _p->faultcode = faultcode; _p->faultstring = faultstring; _p->faultactor = faultactor; _p->detail = detail; _p->SOAP_ENV__Code = SOAP_ENV__Code; _p->SOAP_ENV__Reason = SOAP_ENV__Reason; _p->SOAP_ENV__Node = SOAP_ENV__Node; _p->SOAP_ENV__Role = SOAP_ENV__Role; _p->SOAP_ENV__Detail = SOAP_ENV__Detail; } return _p; }

inline void soap_delete_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_serialize_SOAP_ENV__Reason(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Reason * soap_new_SOAP_ENV__Reason(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Reason * soap_new_req_SOAP_ENV__Reason(struct soap *soap) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); } return _p; }

inline struct SOAP_ENV__Reason * soap_new_set_SOAP_ENV__Reason(struct soap *soap, char *SOAP_ENV__Text) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); _p->SOAP_ENV__Text = SOAP_ENV__Text; } return _p; }

inline void soap_delete_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_serialize_SOAP_ENV__Detail(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Detail * soap_new_SOAP_ENV__Detail(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Detail * soap_new_req_SOAP_ENV__Detail(struct soap *soap, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__type = __type; _p->fault = fault; } return _p; }

inline struct SOAP_ENV__Detail * soap_new_set_SOAP_ENV__Detail(struct soap *soap, char *__any, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__any = __any; _p->__type = __type; _p->fault = fault; } return _p; }

inline void soap_delete_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_serialize_SOAP_ENV__Code(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Code * soap_new_SOAP_ENV__Code(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Code * soap_new_req_SOAP_ENV__Code(struct soap *soap) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); } return _p; }

inline struct SOAP_ENV__Code * soap_new_set_SOAP_ENV__Code(struct soap *soap, char *SOAP_ENV__Value, struct SOAP_ENV__Code *SOAP_ENV__Subcode) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); _p->SOAP_ENV__Value = SOAP_ENV__Value; _p->SOAP_ENV__Subcode = SOAP_ENV__Subcode; } return _p; }

inline void soap_delete_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_serialize_SOAP_ENV__Header(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Header * soap_new_SOAP_ENV__Header(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Header * soap_new_req_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline struct SOAP_ENV__Header * soap_new_set_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline void soap_delete_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns1__getMainKey
#define SOAP_TYPE___ns1__getMainKey (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getMainKey(struct soap*, struct __ns1__getMainKey *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getMainKey(struct soap*, const struct __ns1__getMainKey *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getMainKey(struct soap*, const char*, int, const struct __ns1__getMainKey *, const char*);
SOAP_FMAC3 struct __ns1__getMainKey * SOAP_FMAC4 soap_in___ns1__getMainKey(struct soap*, const char*, struct __ns1__getMainKey *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getMainKey(struct soap*, const struct __ns1__getMainKey *, const char*, const char*);

#ifndef soap_write___ns1__getMainKey
#define soap_write___ns1__getMainKey(soap, data) ( soap_serialize___ns1__getMainKey(soap, data), soap_begin_send(soap) || soap_put___ns1__getMainKey(soap, data, "-ns1:getMainKey", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__getMainKey * SOAP_FMAC4 soap_get___ns1__getMainKey(struct soap*, struct __ns1__getMainKey *, const char*, const char*);

#ifndef soap_read___ns1__getMainKey
#define soap_read___ns1__getMainKey(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__getMainKey(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct __ns1__getMainKey * SOAP_FMAC2 soap_instantiate___ns1__getMainKey(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__getMainKey * soap_new___ns1__getMainKey(struct soap *soap, int n = -1) { return soap_instantiate___ns1__getMainKey(soap, n, NULL, NULL, NULL); }

inline struct __ns1__getMainKey * soap_new_req___ns1__getMainKey(struct soap *soap) { struct __ns1__getMainKey *_p = soap_instantiate___ns1__getMainKey(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__getMainKey(soap, _p); } return _p; }

inline struct __ns1__getMainKey * soap_new_set___ns1__getMainKey(struct soap *soap, ns1__getMainKey *ns1__getMainKey_) { struct __ns1__getMainKey *_p = soap_instantiate___ns1__getMainKey(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__getMainKey(soap, _p); _p->ns1__getMainKey_ = ns1__getMainKey_; } return _p; }

inline void soap_delete___ns1__getMainKey(struct soap *soap, struct __ns1__getMainKey *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getMainKey(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__getCardTypeRules
#define SOAP_TYPE___ns1__getCardTypeRules (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__getCardTypeRules(struct soap*, struct __ns1__getCardTypeRules *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__getCardTypeRules(struct soap*, const struct __ns1__getCardTypeRules *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__getCardTypeRules(struct soap*, const char*, int, const struct __ns1__getCardTypeRules *, const char*);
SOAP_FMAC3 struct __ns1__getCardTypeRules * SOAP_FMAC4 soap_in___ns1__getCardTypeRules(struct soap*, const char*, struct __ns1__getCardTypeRules *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__getCardTypeRules(struct soap*, const struct __ns1__getCardTypeRules *, const char*, const char*);

#ifndef soap_write___ns1__getCardTypeRules
#define soap_write___ns1__getCardTypeRules(soap, data) ( soap_serialize___ns1__getCardTypeRules(soap, data), soap_begin_send(soap) || soap_put___ns1__getCardTypeRules(soap, data, "-ns1:getCardTypeRules", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__getCardTypeRules * SOAP_FMAC4 soap_get___ns1__getCardTypeRules(struct soap*, struct __ns1__getCardTypeRules *, const char*, const char*);

#ifndef soap_read___ns1__getCardTypeRules
#define soap_read___ns1__getCardTypeRules(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__getCardTypeRules(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct __ns1__getCardTypeRules * SOAP_FMAC2 soap_instantiate___ns1__getCardTypeRules(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__getCardTypeRules * soap_new___ns1__getCardTypeRules(struct soap *soap, int n = -1) { return soap_instantiate___ns1__getCardTypeRules(soap, n, NULL, NULL, NULL); }

inline struct __ns1__getCardTypeRules * soap_new_req___ns1__getCardTypeRules(struct soap *soap) { struct __ns1__getCardTypeRules *_p = soap_instantiate___ns1__getCardTypeRules(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__getCardTypeRules(soap, _p); } return _p; }

inline struct __ns1__getCardTypeRules * soap_new_set___ns1__getCardTypeRules(struct soap *soap, ns1__getCardTypeRules *ns1__getCardTypeRules_) { struct __ns1__getCardTypeRules *_p = soap_instantiate___ns1__getCardTypeRules(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__getCardTypeRules(soap, _p); _p->ns1__getCardTypeRules_ = ns1__getCardTypeRules_; } return _p; }

inline void soap_delete___ns1__getCardTypeRules(struct soap *soap, struct __ns1__getCardTypeRules *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__getCardTypeRules(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__storeCard
#define SOAP_TYPE___ns1__storeCard (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__storeCard(struct soap*, struct __ns1__storeCard *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__storeCard(struct soap*, const struct __ns1__storeCard *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__storeCard(struct soap*, const char*, int, const struct __ns1__storeCard *, const char*);
SOAP_FMAC3 struct __ns1__storeCard * SOAP_FMAC4 soap_in___ns1__storeCard(struct soap*, const char*, struct __ns1__storeCard *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__storeCard(struct soap*, const struct __ns1__storeCard *, const char*, const char*);

#ifndef soap_write___ns1__storeCard
#define soap_write___ns1__storeCard(soap, data) ( soap_serialize___ns1__storeCard(soap, data), soap_begin_send(soap) || soap_put___ns1__storeCard(soap, data, "-ns1:storeCard", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__storeCard * SOAP_FMAC4 soap_get___ns1__storeCard(struct soap*, struct __ns1__storeCard *, const char*, const char*);

#ifndef soap_read___ns1__storeCard
#define soap_read___ns1__storeCard(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__storeCard(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct __ns1__storeCard * SOAP_FMAC2 soap_instantiate___ns1__storeCard(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__storeCard * soap_new___ns1__storeCard(struct soap *soap, int n = -1) { return soap_instantiate___ns1__storeCard(soap, n, NULL, NULL, NULL); }

inline struct __ns1__storeCard * soap_new_req___ns1__storeCard(struct soap *soap) { struct __ns1__storeCard *_p = soap_instantiate___ns1__storeCard(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__storeCard(soap, _p); } return _p; }

inline struct __ns1__storeCard * soap_new_set___ns1__storeCard(struct soap *soap, ns1__storeCard *ns1__storeCard_) { struct __ns1__storeCard *_p = soap_instantiate___ns1__storeCard(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__storeCard(soap, _p); _p->ns1__storeCard_ = ns1__storeCard_; } return _p; }

inline void soap_delete___ns1__storeCard(struct soap *soap, struct __ns1__storeCard *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__storeCard(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__generatePassword
#define SOAP_TYPE___ns1__generatePassword (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__generatePassword(struct soap*, struct __ns1__generatePassword *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__generatePassword(struct soap*, const struct __ns1__generatePassword *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__generatePassword(struct soap*, const char*, int, const struct __ns1__generatePassword *, const char*);
SOAP_FMAC3 struct __ns1__generatePassword * SOAP_FMAC4 soap_in___ns1__generatePassword(struct soap*, const char*, struct __ns1__generatePassword *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__generatePassword(struct soap*, const struct __ns1__generatePassword *, const char*, const char*);

#ifndef soap_write___ns1__generatePassword
#define soap_write___ns1__generatePassword(soap, data) ( soap_serialize___ns1__generatePassword(soap, data), soap_begin_send(soap) || soap_put___ns1__generatePassword(soap, data, "-ns1:generatePassword", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__generatePassword * SOAP_FMAC4 soap_get___ns1__generatePassword(struct soap*, struct __ns1__generatePassword *, const char*, const char*);

#ifndef soap_read___ns1__generatePassword
#define soap_read___ns1__generatePassword(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__generatePassword(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct __ns1__generatePassword * SOAP_FMAC2 soap_instantiate___ns1__generatePassword(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__generatePassword * soap_new___ns1__generatePassword(struct soap *soap, int n = -1) { return soap_instantiate___ns1__generatePassword(soap, n, NULL, NULL, NULL); }

inline struct __ns1__generatePassword * soap_new_req___ns1__generatePassword(struct soap *soap) { struct __ns1__generatePassword *_p = soap_instantiate___ns1__generatePassword(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__generatePassword(soap, _p); } return _p; }

inline struct __ns1__generatePassword * soap_new_set___ns1__generatePassword(struct soap *soap, ns1__generatePassword *ns1__generatePassword_) { struct __ns1__generatePassword *_p = soap_instantiate___ns1__generatePassword(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__generatePassword(soap, _p); _p->ns1__generatePassword_ = ns1__generatePassword_; } return _p; }

inline void soap_delete___ns1__generatePassword(struct soap *soap, struct __ns1__generatePassword *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__generatePassword(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__storePsamCard
#define SOAP_TYPE___ns1__storePsamCard (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__storePsamCard(struct soap*, struct __ns1__storePsamCard *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__storePsamCard(struct soap*, const struct __ns1__storePsamCard *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__storePsamCard(struct soap*, const char*, int, const struct __ns1__storePsamCard *, const char*);
SOAP_FMAC3 struct __ns1__storePsamCard * SOAP_FMAC4 soap_in___ns1__storePsamCard(struct soap*, const char*, struct __ns1__storePsamCard *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__storePsamCard(struct soap*, const struct __ns1__storePsamCard *, const char*, const char*);

#ifndef soap_write___ns1__storePsamCard
#define soap_write___ns1__storePsamCard(soap, data) ( soap_serialize___ns1__storePsamCard(soap, data), soap_begin_send(soap) || soap_put___ns1__storePsamCard(soap, data, "-ns1:storePsamCard", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__storePsamCard * SOAP_FMAC4 soap_get___ns1__storePsamCard(struct soap*, struct __ns1__storePsamCard *, const char*, const char*);

#ifndef soap_read___ns1__storePsamCard
#define soap_read___ns1__storePsamCard(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__storePsamCard(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct __ns1__storePsamCard * SOAP_FMAC2 soap_instantiate___ns1__storePsamCard(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__storePsamCard * soap_new___ns1__storePsamCard(struct soap *soap, int n = -1) { return soap_instantiate___ns1__storePsamCard(soap, n, NULL, NULL, NULL); }

inline struct __ns1__storePsamCard * soap_new_req___ns1__storePsamCard(struct soap *soap) { struct __ns1__storePsamCard *_p = soap_instantiate___ns1__storePsamCard(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__storePsamCard(soap, _p); } return _p; }

inline struct __ns1__storePsamCard * soap_new_set___ns1__storePsamCard(struct soap *soap, ns1__storePsamCard *ns1__storePsamCard_) { struct __ns1__storePsamCard *_p = soap_instantiate___ns1__storePsamCard(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__storePsamCard(soap, _p); _p->ns1__storePsamCard_ = ns1__storePsamCard_; } return _p; }

inline void soap_delete___ns1__storePsamCard(struct soap *soap, struct __ns1__storePsamCard *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__storePsamCard(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__generatePsamCardNo
#define SOAP_TYPE___ns1__generatePsamCardNo (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__generatePsamCardNo(struct soap*, struct __ns1__generatePsamCardNo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__generatePsamCardNo(struct soap*, const struct __ns1__generatePsamCardNo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__generatePsamCardNo(struct soap*, const char*, int, const struct __ns1__generatePsamCardNo *, const char*);
SOAP_FMAC3 struct __ns1__generatePsamCardNo * SOAP_FMAC4 soap_in___ns1__generatePsamCardNo(struct soap*, const char*, struct __ns1__generatePsamCardNo *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__generatePsamCardNo(struct soap*, const struct __ns1__generatePsamCardNo *, const char*, const char*);

#ifndef soap_write___ns1__generatePsamCardNo
#define soap_write___ns1__generatePsamCardNo(soap, data) ( soap_serialize___ns1__generatePsamCardNo(soap, data), soap_begin_send(soap) || soap_put___ns1__generatePsamCardNo(soap, data, "-ns1:generatePsamCardNo", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__generatePsamCardNo * SOAP_FMAC4 soap_get___ns1__generatePsamCardNo(struct soap*, struct __ns1__generatePsamCardNo *, const char*, const char*);

#ifndef soap_read___ns1__generatePsamCardNo
#define soap_read___ns1__generatePsamCardNo(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__generatePsamCardNo(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct __ns1__generatePsamCardNo * SOAP_FMAC2 soap_instantiate___ns1__generatePsamCardNo(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__generatePsamCardNo * soap_new___ns1__generatePsamCardNo(struct soap *soap, int n = -1) { return soap_instantiate___ns1__generatePsamCardNo(soap, n, NULL, NULL, NULL); }

inline struct __ns1__generatePsamCardNo * soap_new_req___ns1__generatePsamCardNo(struct soap *soap) { struct __ns1__generatePsamCardNo *_p = soap_instantiate___ns1__generatePsamCardNo(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__generatePsamCardNo(soap, _p); } return _p; }

inline struct __ns1__generatePsamCardNo * soap_new_set___ns1__generatePsamCardNo(struct soap *soap, ns1__generatePsamCardNo *ns1__generatePsamCardNo_) { struct __ns1__generatePsamCardNo *_p = soap_instantiate___ns1__generatePsamCardNo(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__generatePsamCardNo(soap, _p); _p->ns1__generatePsamCardNo_ = ns1__generatePsamCardNo_; } return _p; }

inline void soap_delete___ns1__generatePsamCardNo(struct soap *soap, struct __ns1__generatePsamCardNo *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__generatePsamCardNo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__verifyUser
#define SOAP_TYPE___ns1__verifyUser (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__verifyUser(struct soap*, struct __ns1__verifyUser *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__verifyUser(struct soap*, const struct __ns1__verifyUser *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__verifyUser(struct soap*, const char*, int, const struct __ns1__verifyUser *, const char*);
SOAP_FMAC3 struct __ns1__verifyUser * SOAP_FMAC4 soap_in___ns1__verifyUser(struct soap*, const char*, struct __ns1__verifyUser *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__verifyUser(struct soap*, const struct __ns1__verifyUser *, const char*, const char*);

#ifndef soap_write___ns1__verifyUser
#define soap_write___ns1__verifyUser(soap, data) ( soap_serialize___ns1__verifyUser(soap, data), soap_begin_send(soap) || soap_put___ns1__verifyUser(soap, data, "-ns1:verifyUser", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct __ns1__verifyUser * SOAP_FMAC4 soap_get___ns1__verifyUser(struct soap*, struct __ns1__verifyUser *, const char*, const char*);

#ifndef soap_read___ns1__verifyUser
#define soap_read___ns1__verifyUser(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__verifyUser(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct __ns1__verifyUser * SOAP_FMAC2 soap_instantiate___ns1__verifyUser(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__verifyUser * soap_new___ns1__verifyUser(struct soap *soap, int n = -1) { return soap_instantiate___ns1__verifyUser(soap, n, NULL, NULL, NULL); }

inline struct __ns1__verifyUser * soap_new_req___ns1__verifyUser(struct soap *soap) { struct __ns1__verifyUser *_p = soap_instantiate___ns1__verifyUser(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__verifyUser(soap, _p); } return _p; }

inline struct __ns1__verifyUser * soap_new_set___ns1__verifyUser(struct soap *soap, ns1__verifyUser *ns1__verifyUser_) { struct __ns1__verifyUser *_p = soap_instantiate___ns1__verifyUser(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__verifyUser(soap, _p); _p->ns1__verifyUser_ = ns1__verifyUser_; } return _p; }

inline void soap_delete___ns1__verifyUser(struct soap *soap, struct __ns1__verifyUser *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__verifyUser(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_serialize_PointerToSOAP_ENV__Reason(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_serialize_PointerToSOAP_ENV__Detail(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_serialize_PointerToSOAP_ENV__Code(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef SOAP_TYPE_PointerTons1__getMainKeyResponse
#define SOAP_TYPE_PointerTons1__getMainKeyResponse (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__getMainKeyResponse(struct soap*, ns1__getMainKeyResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__getMainKeyResponse(struct soap*, const char *, int, ns1__getMainKeyResponse *const*, const char *);
SOAP_FMAC3 ns1__getMainKeyResponse ** SOAP_FMAC4 soap_in_PointerTons1__getMainKeyResponse(struct soap*, const char*, ns1__getMainKeyResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__getMainKeyResponse(struct soap*, ns1__getMainKeyResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__getMainKeyResponse
#define soap_write_PointerTons1__getMainKeyResponse(soap, data) ( soap_serialize_PointerTons1__getMainKeyResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__getMainKeyResponse(soap, data, "ns1:getMainKeyResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__getMainKeyResponse ** SOAP_FMAC4 soap_get_PointerTons1__getMainKeyResponse(struct soap*, ns1__getMainKeyResponse **, const char*, const char*);

#ifndef soap_read_PointerTons1__getMainKeyResponse
#define soap_read_PointerTons1__getMainKeyResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__getMainKeyResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__getMainKey
#define SOAP_TYPE_PointerTons1__getMainKey (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__getMainKey(struct soap*, ns1__getMainKey *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__getMainKey(struct soap*, const char *, int, ns1__getMainKey *const*, const char *);
SOAP_FMAC3 ns1__getMainKey ** SOAP_FMAC4 soap_in_PointerTons1__getMainKey(struct soap*, const char*, ns1__getMainKey **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__getMainKey(struct soap*, ns1__getMainKey *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__getMainKey
#define soap_write_PointerTons1__getMainKey(soap, data) ( soap_serialize_PointerTons1__getMainKey(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__getMainKey(soap, data, "ns1:getMainKey", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__getMainKey ** SOAP_FMAC4 soap_get_PointerTons1__getMainKey(struct soap*, ns1__getMainKey **, const char*, const char*);

#ifndef soap_read_PointerTons1__getMainKey
#define soap_read_PointerTons1__getMainKey(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__getMainKey(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__getCardTypeRulesResponse
#define SOAP_TYPE_PointerTons1__getCardTypeRulesResponse (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__getCardTypeRulesResponse(struct soap*, ns1__getCardTypeRulesResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__getCardTypeRulesResponse(struct soap*, const char *, int, ns1__getCardTypeRulesResponse *const*, const char *);
SOAP_FMAC3 ns1__getCardTypeRulesResponse ** SOAP_FMAC4 soap_in_PointerTons1__getCardTypeRulesResponse(struct soap*, const char*, ns1__getCardTypeRulesResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__getCardTypeRulesResponse(struct soap*, ns1__getCardTypeRulesResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__getCardTypeRulesResponse
#define soap_write_PointerTons1__getCardTypeRulesResponse(soap, data) ( soap_serialize_PointerTons1__getCardTypeRulesResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__getCardTypeRulesResponse(soap, data, "ns1:getCardTypeRulesResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__getCardTypeRulesResponse ** SOAP_FMAC4 soap_get_PointerTons1__getCardTypeRulesResponse(struct soap*, ns1__getCardTypeRulesResponse **, const char*, const char*);

#ifndef soap_read_PointerTons1__getCardTypeRulesResponse
#define soap_read_PointerTons1__getCardTypeRulesResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__getCardTypeRulesResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__getCardTypeRules
#define SOAP_TYPE_PointerTons1__getCardTypeRules (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__getCardTypeRules(struct soap*, ns1__getCardTypeRules *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__getCardTypeRules(struct soap*, const char *, int, ns1__getCardTypeRules *const*, const char *);
SOAP_FMAC3 ns1__getCardTypeRules ** SOAP_FMAC4 soap_in_PointerTons1__getCardTypeRules(struct soap*, const char*, ns1__getCardTypeRules **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__getCardTypeRules(struct soap*, ns1__getCardTypeRules *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__getCardTypeRules
#define soap_write_PointerTons1__getCardTypeRules(soap, data) ( soap_serialize_PointerTons1__getCardTypeRules(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__getCardTypeRules(soap, data, "ns1:getCardTypeRules", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__getCardTypeRules ** SOAP_FMAC4 soap_get_PointerTons1__getCardTypeRules(struct soap*, ns1__getCardTypeRules **, const char*, const char*);

#ifndef soap_read_PointerTons1__getCardTypeRules
#define soap_read_PointerTons1__getCardTypeRules(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__getCardTypeRules(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__storeCardResponse
#define SOAP_TYPE_PointerTons1__storeCardResponse (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__storeCardResponse(struct soap*, ns1__storeCardResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__storeCardResponse(struct soap*, const char *, int, ns1__storeCardResponse *const*, const char *);
SOAP_FMAC3 ns1__storeCardResponse ** SOAP_FMAC4 soap_in_PointerTons1__storeCardResponse(struct soap*, const char*, ns1__storeCardResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__storeCardResponse(struct soap*, ns1__storeCardResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__storeCardResponse
#define soap_write_PointerTons1__storeCardResponse(soap, data) ( soap_serialize_PointerTons1__storeCardResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__storeCardResponse(soap, data, "ns1:storeCardResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__storeCardResponse ** SOAP_FMAC4 soap_get_PointerTons1__storeCardResponse(struct soap*, ns1__storeCardResponse **, const char*, const char*);

#ifndef soap_read_PointerTons1__storeCardResponse
#define soap_read_PointerTons1__storeCardResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__storeCardResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__storeCard
#define SOAP_TYPE_PointerTons1__storeCard (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__storeCard(struct soap*, ns1__storeCard *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__storeCard(struct soap*, const char *, int, ns1__storeCard *const*, const char *);
SOAP_FMAC3 ns1__storeCard ** SOAP_FMAC4 soap_in_PointerTons1__storeCard(struct soap*, const char*, ns1__storeCard **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__storeCard(struct soap*, ns1__storeCard *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__storeCard
#define soap_write_PointerTons1__storeCard(soap, data) ( soap_serialize_PointerTons1__storeCard(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__storeCard(soap, data, "ns1:storeCard", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__storeCard ** SOAP_FMAC4 soap_get_PointerTons1__storeCard(struct soap*, ns1__storeCard **, const char*, const char*);

#ifndef soap_read_PointerTons1__storeCard
#define soap_read_PointerTons1__storeCard(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__storeCard(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__generatePasswordResponse
#define SOAP_TYPE_PointerTons1__generatePasswordResponse (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__generatePasswordResponse(struct soap*, ns1__generatePasswordResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__generatePasswordResponse(struct soap*, const char *, int, ns1__generatePasswordResponse *const*, const char *);
SOAP_FMAC3 ns1__generatePasswordResponse ** SOAP_FMAC4 soap_in_PointerTons1__generatePasswordResponse(struct soap*, const char*, ns1__generatePasswordResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__generatePasswordResponse(struct soap*, ns1__generatePasswordResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__generatePasswordResponse
#define soap_write_PointerTons1__generatePasswordResponse(soap, data) ( soap_serialize_PointerTons1__generatePasswordResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__generatePasswordResponse(soap, data, "ns1:generatePasswordResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__generatePasswordResponse ** SOAP_FMAC4 soap_get_PointerTons1__generatePasswordResponse(struct soap*, ns1__generatePasswordResponse **, const char*, const char*);

#ifndef soap_read_PointerTons1__generatePasswordResponse
#define soap_read_PointerTons1__generatePasswordResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__generatePasswordResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__generatePassword
#define SOAP_TYPE_PointerTons1__generatePassword (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__generatePassword(struct soap*, ns1__generatePassword *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__generatePassword(struct soap*, const char *, int, ns1__generatePassword *const*, const char *);
SOAP_FMAC3 ns1__generatePassword ** SOAP_FMAC4 soap_in_PointerTons1__generatePassword(struct soap*, const char*, ns1__generatePassword **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__generatePassword(struct soap*, ns1__generatePassword *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__generatePassword
#define soap_write_PointerTons1__generatePassword(soap, data) ( soap_serialize_PointerTons1__generatePassword(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__generatePassword(soap, data, "ns1:generatePassword", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__generatePassword ** SOAP_FMAC4 soap_get_PointerTons1__generatePassword(struct soap*, ns1__generatePassword **, const char*, const char*);

#ifndef soap_read_PointerTons1__generatePassword
#define soap_read_PointerTons1__generatePassword(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__generatePassword(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__storePsamCardResponse
#define SOAP_TYPE_PointerTons1__storePsamCardResponse (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__storePsamCardResponse(struct soap*, ns1__storePsamCardResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__storePsamCardResponse(struct soap*, const char *, int, ns1__storePsamCardResponse *const*, const char *);
SOAP_FMAC3 ns1__storePsamCardResponse ** SOAP_FMAC4 soap_in_PointerTons1__storePsamCardResponse(struct soap*, const char*, ns1__storePsamCardResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__storePsamCardResponse(struct soap*, ns1__storePsamCardResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__storePsamCardResponse
#define soap_write_PointerTons1__storePsamCardResponse(soap, data) ( soap_serialize_PointerTons1__storePsamCardResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__storePsamCardResponse(soap, data, "ns1:storePsamCardResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__storePsamCardResponse ** SOAP_FMAC4 soap_get_PointerTons1__storePsamCardResponse(struct soap*, ns1__storePsamCardResponse **, const char*, const char*);

#ifndef soap_read_PointerTons1__storePsamCardResponse
#define soap_read_PointerTons1__storePsamCardResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__storePsamCardResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__storePsamCard
#define SOAP_TYPE_PointerTons1__storePsamCard (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__storePsamCard(struct soap*, ns1__storePsamCard *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__storePsamCard(struct soap*, const char *, int, ns1__storePsamCard *const*, const char *);
SOAP_FMAC3 ns1__storePsamCard ** SOAP_FMAC4 soap_in_PointerTons1__storePsamCard(struct soap*, const char*, ns1__storePsamCard **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__storePsamCard(struct soap*, ns1__storePsamCard *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__storePsamCard
#define soap_write_PointerTons1__storePsamCard(soap, data) ( soap_serialize_PointerTons1__storePsamCard(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__storePsamCard(soap, data, "ns1:storePsamCard", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__storePsamCard ** SOAP_FMAC4 soap_get_PointerTons1__storePsamCard(struct soap*, ns1__storePsamCard **, const char*, const char*);

#ifndef soap_read_PointerTons1__storePsamCard
#define soap_read_PointerTons1__storePsamCard(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__storePsamCard(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__generatePsamCardNoResponse
#define SOAP_TYPE_PointerTons1__generatePsamCardNoResponse (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__generatePsamCardNoResponse(struct soap*, ns1__generatePsamCardNoResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__generatePsamCardNoResponse(struct soap*, const char *, int, ns1__generatePsamCardNoResponse *const*, const char *);
SOAP_FMAC3 ns1__generatePsamCardNoResponse ** SOAP_FMAC4 soap_in_PointerTons1__generatePsamCardNoResponse(struct soap*, const char*, ns1__generatePsamCardNoResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__generatePsamCardNoResponse(struct soap*, ns1__generatePsamCardNoResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__generatePsamCardNoResponse
#define soap_write_PointerTons1__generatePsamCardNoResponse(soap, data) ( soap_serialize_PointerTons1__generatePsamCardNoResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__generatePsamCardNoResponse(soap, data, "ns1:generatePsamCardNoResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__generatePsamCardNoResponse ** SOAP_FMAC4 soap_get_PointerTons1__generatePsamCardNoResponse(struct soap*, ns1__generatePsamCardNoResponse **, const char*, const char*);

#ifndef soap_read_PointerTons1__generatePsamCardNoResponse
#define soap_read_PointerTons1__generatePsamCardNoResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__generatePsamCardNoResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__generatePsamCardNo
#define SOAP_TYPE_PointerTons1__generatePsamCardNo (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__generatePsamCardNo(struct soap*, ns1__generatePsamCardNo *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__generatePsamCardNo(struct soap*, const char *, int, ns1__generatePsamCardNo *const*, const char *);
SOAP_FMAC3 ns1__generatePsamCardNo ** SOAP_FMAC4 soap_in_PointerTons1__generatePsamCardNo(struct soap*, const char*, ns1__generatePsamCardNo **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__generatePsamCardNo(struct soap*, ns1__generatePsamCardNo *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__generatePsamCardNo
#define soap_write_PointerTons1__generatePsamCardNo(soap, data) ( soap_serialize_PointerTons1__generatePsamCardNo(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__generatePsamCardNo(soap, data, "ns1:generatePsamCardNo", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__generatePsamCardNo ** SOAP_FMAC4 soap_get_PointerTons1__generatePsamCardNo(struct soap*, ns1__generatePsamCardNo **, const char*, const char*);

#ifndef soap_read_PointerTons1__generatePsamCardNo
#define soap_read_PointerTons1__generatePsamCardNo(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__generatePsamCardNo(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__verifyUserResponse
#define SOAP_TYPE_PointerTons1__verifyUserResponse (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__verifyUserResponse(struct soap*, ns1__verifyUserResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__verifyUserResponse(struct soap*, const char *, int, ns1__verifyUserResponse *const*, const char *);
SOAP_FMAC3 ns1__verifyUserResponse ** SOAP_FMAC4 soap_in_PointerTons1__verifyUserResponse(struct soap*, const char*, ns1__verifyUserResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__verifyUserResponse(struct soap*, ns1__verifyUserResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__verifyUserResponse
#define soap_write_PointerTons1__verifyUserResponse(soap, data) ( soap_serialize_PointerTons1__verifyUserResponse(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__verifyUserResponse(soap, data, "ns1:verifyUserResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__verifyUserResponse ** SOAP_FMAC4 soap_get_PointerTons1__verifyUserResponse(struct soap*, ns1__verifyUserResponse **, const char*, const char*);

#ifndef soap_read_PointerTons1__verifyUserResponse
#define soap_read_PointerTons1__verifyUserResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__verifyUserResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons1__verifyUser
#define SOAP_TYPE_PointerTons1__verifyUser (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__verifyUser(struct soap*, ns1__verifyUser *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__verifyUser(struct soap*, const char *, int, ns1__verifyUser *const*, const char *);
SOAP_FMAC3 ns1__verifyUser ** SOAP_FMAC4 soap_in_PointerTons1__verifyUser(struct soap*, const char*, ns1__verifyUser **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__verifyUser(struct soap*, ns1__verifyUser *const*, const char*, const char*);

#ifndef soap_write_PointerTons1__verifyUser
#define soap_write_PointerTons1__verifyUser(soap, data) ( soap_serialize_PointerTons1__verifyUser(soap, data), soap_begin_send(soap) || soap_put_PointerTons1__verifyUser(soap, data, "ns1:verifyUser", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 ns1__verifyUser ** SOAP_FMAC4 soap_get_PointerTons1__verifyUser(struct soap*, ns1__verifyUser **, const char*, const char*);

#ifndef soap_read_PointerTons1__verifyUser
#define soap_read_PointerTons1__verifyUser(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__verifyUser(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_serialize__QName(soap, data), soap_begin_send(soap) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_serialize_string(soap, data), soap_begin_send(soap) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

/* End of soapH.h */
