/* wpsoap.h
   Generated by wsdl2h 2.8.15 from http://127.0.0.1:8080/services/printerService?wsdl and typemap.dat
   2013-08-25 18:27:03 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2000-2013 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Usage Notes

NOTE:

 - Run soapcpp2 on wpsoap.h to generate the SOAP/XML processing logic.
   Use soapcpp2 -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 -j to generate improved proxy and server classes.
 - Use wsdl2h -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -R to generate REST operations.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Use wsdl2h -d to enable DOM support for xsd:anyType.
 - Use wsdl2h -g to auto-generate readers and writers for root elements.
 - Use wsdl2h -b to auto-generate bi-directional operations (duplex ops).
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

WARNING:

   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

LICENSE:

@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following two licenses:
GPL or Genivia's license for commercial use.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://service.ws.redcard.com/                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "http://service.ws.redcard.com/"

*/

#define SOAP_NAMESPACE_OF_ns1	"http://service.ws.redcard.com/"
//gsoap ns1   schema namespace:	http://service.ws.redcard.com/
//gsoap ns1   schema form:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/



//  Forward declaration of class ns1__verifyUser.
class ns1__verifyUser;

//  Forward declaration of class ns1__verifyUserResponse.
class ns1__verifyUserResponse;

//  Forward declaration of class ns1__storePsamCard.
class ns1__storePsamCard;

//  Forward declaration of class ns1__storePsamCardResponse.
class ns1__storePsamCardResponse;

//  Forward declaration of class ns1__generatePsamCardNo.
class ns1__generatePsamCardNo;

//  Forward declaration of class ns1__generatePsamCardNoResponse.
class ns1__generatePsamCardNoResponse;

//  Forward declaration of class ns1__generatePassword.
class ns1__generatePassword;

//  Forward declaration of class ns1__generatePasswordResponse.
class ns1__generatePasswordResponse;

//  Forward declaration of class ns1__storeCard.
class ns1__storeCard;

//  Forward declaration of class ns1__storeCardResponse.
class ns1__storeCardResponse;

//  Forward declaration of class ns1__getCardTypeRules.
class ns1__getCardTypeRules;

//  Forward declaration of class ns1__getCardTypeRulesResponse.
class ns1__getCardTypeRulesResponse;

//  Forward declaration of class ns1__getMainKey.
class ns1__getMainKey;

//  Forward declaration of class ns1__getMainKeyResponse.
class ns1__getMainKeyResponse;

/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://service.ws.redcard.com/                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://service.ws.redcard.com/                                           *
 *                                                                            *
\******************************************************************************/


/// "http://service.ws.redcard.com/":verifyUser is a complexType.
/// class ns1__verifyUser operations:
/// - soap_new_ns1__verifyUser(soap*) allocate
/// - soap_new_ns1__verifyUser(soap*, int num) allocate array
/// - soap_new_req_ns1__verifyUser(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__verifyUser(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__verifyUser(soap*, ns1__verifyUser*) deserialize from a stream
/// - int soap_write_ns1__verifyUser(soap, ns1__verifyUser*) serialize to a stream
class ns1__verifyUser
{ public:
/// Element arg0 of type xs:string.
    char*                                arg0                           0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://service.ws.redcard.com/":verifyUserResponse is a complexType.
/// class ns1__verifyUserResponse operations:
/// - soap_new_ns1__verifyUserResponse(soap*) allocate
/// - soap_new_ns1__verifyUserResponse(soap*, int num) allocate array
/// - soap_new_req_ns1__verifyUserResponse(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__verifyUserResponse(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__verifyUserResponse(soap*, ns1__verifyUserResponse*) deserialize from a stream
/// - int soap_write_ns1__verifyUserResponse(soap, ns1__verifyUserResponse*) serialize to a stream
class ns1__verifyUserResponse
{ public:
/// Element return of type xs:string.
    char*                                return_                        0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://service.ws.redcard.com/":storePsamCard is a complexType.
/// class ns1__storePsamCard operations:
/// - soap_new_ns1__storePsamCard(soap*) allocate
/// - soap_new_ns1__storePsamCard(soap*, int num) allocate array
/// - soap_new_req_ns1__storePsamCard(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__storePsamCard(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__storePsamCard(soap*, ns1__storePsamCard*) deserialize from a stream
/// - int soap_write_ns1__storePsamCard(soap, ns1__storePsamCard*) serialize to a stream
class ns1__storePsamCard
{ public:
/// Element arg0 of type xs:string.
    char*                                arg0                           0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://service.ws.redcard.com/":storePsamCardResponse is a complexType.
/// class ns1__storePsamCardResponse operations:
/// - soap_new_ns1__storePsamCardResponse(soap*) allocate
/// - soap_new_ns1__storePsamCardResponse(soap*, int num) allocate array
/// - soap_new_req_ns1__storePsamCardResponse(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__storePsamCardResponse(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__storePsamCardResponse(soap*, ns1__storePsamCardResponse*) deserialize from a stream
/// - int soap_write_ns1__storePsamCardResponse(soap, ns1__storePsamCardResponse*) serialize to a stream
class ns1__storePsamCardResponse
{ public:
/// Element return of type xs:string.
    char*                                return_                        0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://service.ws.redcard.com/":generatePsamCardNo is a complexType.
/// class ns1__generatePsamCardNo operations:
/// - soap_new_ns1__generatePsamCardNo(soap*) allocate
/// - soap_new_ns1__generatePsamCardNo(soap*, int num) allocate array
/// - soap_new_req_ns1__generatePsamCardNo(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__generatePsamCardNo(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__generatePsamCardNo(soap*, ns1__generatePsamCardNo*) deserialize from a stream
/// - int soap_write_ns1__generatePsamCardNo(soap, ns1__generatePsamCardNo*) serialize to a stream
class ns1__generatePsamCardNo
{ public:
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://service.ws.redcard.com/":generatePsamCardNoResponse is a complexType.
/// class ns1__generatePsamCardNoResponse operations:
/// - soap_new_ns1__generatePsamCardNoResponse(soap*) allocate
/// - soap_new_ns1__generatePsamCardNoResponse(soap*, int num) allocate array
/// - soap_new_req_ns1__generatePsamCardNoResponse(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__generatePsamCardNoResponse(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__generatePsamCardNoResponse(soap*, ns1__generatePsamCardNoResponse*) deserialize from a stream
/// - int soap_write_ns1__generatePsamCardNoResponse(soap, ns1__generatePsamCardNoResponse*) serialize to a stream
class ns1__generatePsamCardNoResponse
{ public:
/// Element return of type xs:string.
    char*                                return_                        0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://service.ws.redcard.com/":generatePassword is a complexType.
/// class ns1__generatePassword operations:
/// - soap_new_ns1__generatePassword(soap*) allocate
/// - soap_new_ns1__generatePassword(soap*, int num) allocate array
/// - soap_new_req_ns1__generatePassword(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__generatePassword(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__generatePassword(soap*, ns1__generatePassword*) deserialize from a stream
/// - int soap_write_ns1__generatePassword(soap, ns1__generatePassword*) serialize to a stream
class ns1__generatePassword
{ public:
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://service.ws.redcard.com/":generatePasswordResponse is a complexType.
/// class ns1__generatePasswordResponse operations:
/// - soap_new_ns1__generatePasswordResponse(soap*) allocate
/// - soap_new_ns1__generatePasswordResponse(soap*, int num) allocate array
/// - soap_new_req_ns1__generatePasswordResponse(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__generatePasswordResponse(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__generatePasswordResponse(soap*, ns1__generatePasswordResponse*) deserialize from a stream
/// - int soap_write_ns1__generatePasswordResponse(soap, ns1__generatePasswordResponse*) serialize to a stream
class ns1__generatePasswordResponse
{ public:
/// Element return of type xs:string.
    char*                                return_                        0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://service.ws.redcard.com/":storeCard is a complexType.
/// class ns1__storeCard operations:
/// - soap_new_ns1__storeCard(soap*) allocate
/// - soap_new_ns1__storeCard(soap*, int num) allocate array
/// - soap_new_req_ns1__storeCard(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__storeCard(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__storeCard(soap*, ns1__storeCard*) deserialize from a stream
/// - int soap_write_ns1__storeCard(soap, ns1__storeCard*) serialize to a stream
class ns1__storeCard
{ public:
/// Element arg0 of type xs:string.
    char*                                arg0                           0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://service.ws.redcard.com/":storeCardResponse is a complexType.
/// class ns1__storeCardResponse operations:
/// - soap_new_ns1__storeCardResponse(soap*) allocate
/// - soap_new_ns1__storeCardResponse(soap*, int num) allocate array
/// - soap_new_req_ns1__storeCardResponse(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__storeCardResponse(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__storeCardResponse(soap*, ns1__storeCardResponse*) deserialize from a stream
/// - int soap_write_ns1__storeCardResponse(soap, ns1__storeCardResponse*) serialize to a stream
class ns1__storeCardResponse
{ public:
/// Element return of type xs:string.
    char*                                return_                        0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://service.ws.redcard.com/":getCardTypeRules is a complexType.
/// class ns1__getCardTypeRules operations:
/// - soap_new_ns1__getCardTypeRules(soap*) allocate
/// - soap_new_ns1__getCardTypeRules(soap*, int num) allocate array
/// - soap_new_req_ns1__getCardTypeRules(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__getCardTypeRules(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__getCardTypeRules(soap*, ns1__getCardTypeRules*) deserialize from a stream
/// - int soap_write_ns1__getCardTypeRules(soap, ns1__getCardTypeRules*) serialize to a stream
class ns1__getCardTypeRules
{ public:
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://service.ws.redcard.com/":getCardTypeRulesResponse is a complexType.
/// class ns1__getCardTypeRulesResponse operations:
/// - soap_new_ns1__getCardTypeRulesResponse(soap*) allocate
/// - soap_new_ns1__getCardTypeRulesResponse(soap*, int num) allocate array
/// - soap_new_req_ns1__getCardTypeRulesResponse(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__getCardTypeRulesResponse(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__getCardTypeRulesResponse(soap*, ns1__getCardTypeRulesResponse*) deserialize from a stream
/// - int soap_write_ns1__getCardTypeRulesResponse(soap, ns1__getCardTypeRulesResponse*) serialize to a stream
class ns1__getCardTypeRulesResponse
{ public:
/// Element return of type xs:string.
    char*                                return_                        0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://service.ws.redcard.com/":getMainKey is a complexType.
/// class ns1__getMainKey operations:
/// - soap_new_ns1__getMainKey(soap*) allocate
/// - soap_new_ns1__getMainKey(soap*, int num) allocate array
/// - soap_new_req_ns1__getMainKey(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__getMainKey(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__getMainKey(soap*, ns1__getMainKey*) deserialize from a stream
/// - int soap_write_ns1__getMainKey(soap, ns1__getMainKey*) serialize to a stream
class ns1__getMainKey
{ public:
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://service.ws.redcard.com/":getMainKeyResponse is a complexType.
/// class ns1__getMainKeyResponse operations:
/// - soap_new_ns1__getMainKeyResponse(soap*) allocate
/// - soap_new_ns1__getMainKeyResponse(soap*, int num) allocate array
/// - soap_new_req_ns1__getMainKeyResponse(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__getMainKeyResponse(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__getMainKeyResponse(soap*, ns1__getMainKeyResponse*) deserialize from a stream
/// - int soap_write_ns1__getMainKeyResponse(soap, ns1__getMainKeyResponse*) serialize to a stream
class ns1__getMainKeyResponse
{ public:
/// Element return of type xs:string.
    char*                                return_                        0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://service.ws.redcard.com/                                           *
 *                                                                            *
\******************************************************************************/


/// Top-level root element "http://service.ws.redcard.com/":generatePassword of type "http://service.ws.redcard.com/":generatePassword.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://service.ws.redcard.com/":generatePasswordResponse of type "http://service.ws.redcard.com/":generatePasswordResponse.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://service.ws.redcard.com/":generatePsamCardNo of type "http://service.ws.redcard.com/":generatePsamCardNo.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://service.ws.redcard.com/":generatePsamCardNoResponse of type "http://service.ws.redcard.com/":generatePsamCardNoResponse.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://service.ws.redcard.com/":getCardTypeRules of type "http://service.ws.redcard.com/":getCardTypeRules.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://service.ws.redcard.com/":getCardTypeRulesResponse of type "http://service.ws.redcard.com/":getCardTypeRulesResponse.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://service.ws.redcard.com/":getMainKey of type "http://service.ws.redcard.com/":getMainKey.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://service.ws.redcard.com/":getMainKeyResponse of type "http://service.ws.redcard.com/":getMainKeyResponse.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://service.ws.redcard.com/":storeCard of type "http://service.ws.redcard.com/":storeCard.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://service.ws.redcard.com/":storeCardResponse of type "http://service.ws.redcard.com/":storeCardResponse.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://service.ws.redcard.com/":storePsamCard of type "http://service.ws.redcard.com/":storePsamCard.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://service.ws.redcard.com/":storePsamCardResponse of type "http://service.ws.redcard.com/":storePsamCardResponse.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://service.ws.redcard.com/":verifyUser of type "http://service.ws.redcard.com/":verifyUser.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// Top-level root element "http://service.ws.redcard.com/":verifyUserResponse of type "http://service.ws.redcard.com/":verifyUserResponse.
/// Note: use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://service.ws.redcard.com/                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns1  service name:	PrinterServiceServiceSoapBinding 
//gsoap ns1  service type:	IPrinter 
//gsoap ns1  service port:	http://127.0.0.1:8080/services/printerService 
//gsoap ns1  service namespace:	http://service.ws.redcard.com/ 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage PrinterServiceService Definitions

@section PrinterServiceService_bindings Service Bindings

  - @ref PrinterServiceServiceSoapBinding

@section PrinterServiceService_more More Information

  - @ref page_notes "Usage Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page PrinterServiceServiceSoapBinding Binding "PrinterServiceServiceSoapBinding"

@section PrinterServiceServiceSoapBinding_operations Operations of Binding  "PrinterServiceServiceSoapBinding"

  - @ref __ns1__verifyUser

  - @ref __ns1__generatePsamCardNo

  - @ref __ns1__storePsamCard

  - @ref __ns1__generatePassword

  - @ref __ns1__storeCard

  - @ref __ns1__getCardTypeRules

  - @ref __ns1__getMainKey

@section PrinterServiceServiceSoapBinding_ports Endpoints of Binding  "PrinterServiceServiceSoapBinding"

  - http://127.0.0.1:8080/services/printerService

Note: use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   PrinterServiceServiceSoapBinding                                         *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__verifyUser                                                        *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__verifyUser" of service binding "PrinterServiceServiceSoapBinding"

/**

Operation details:

  - SOAP document/literal style messaging

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__verifyUser(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    ns1__verifyUser*                    ns1__verifyUser_,
    // output parameters:
    ns1__verifyUserResponse*            ns1__verifyUserResponse_
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__verifyUser(
    struct soap *soap,
    // input parameters:
    ns1__verifyUser*                    ns1__verifyUser_,
    // output parameters:
    ns1__verifyUserResponse*            ns1__verifyUserResponse_
  );
@endcode

C++ proxy class (defined in soapPrinterServiceServiceSoapBindingProxy.h):
@code
  class PrinterServiceServiceSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapPrinterServiceServiceSoapBindingService.h):
@code
  class PrinterServiceServiceSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	verifyUser SOAP
//gsoap ns1  service method-style:	verifyUser document
//gsoap ns1  service method-encoding:	verifyUser literal
//gsoap ns1  service method-action:	verifyUser ""
//gsoap ns1  service method-output-action:	verifyUser Response
int __ns1__verifyUser(
    ns1__verifyUser*                    ns1__verifyUser_,	///< Input parameter
    ns1__verifyUserResponse*            ns1__verifyUserResponse_	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__generatePsamCardNo                                                *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__generatePsamCardNo" of service binding "PrinterServiceServiceSoapBinding"

/**

Operation details:

  - SOAP document/literal style messaging

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__generatePsamCardNo(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    ns1__generatePsamCardNo*            ns1__generatePsamCardNo_,
    // output parameters:
    ns1__generatePsamCardNoResponse*    ns1__generatePsamCardNoResponse_
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__generatePsamCardNo(
    struct soap *soap,
    // input parameters:
    ns1__generatePsamCardNo*            ns1__generatePsamCardNo_,
    // output parameters:
    ns1__generatePsamCardNoResponse*    ns1__generatePsamCardNoResponse_
  );
@endcode

C++ proxy class (defined in soapPrinterServiceServiceSoapBindingProxy.h):
@code
  class PrinterServiceServiceSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapPrinterServiceServiceSoapBindingService.h):
@code
  class PrinterServiceServiceSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	generatePsamCardNo SOAP
//gsoap ns1  service method-style:	generatePsamCardNo document
//gsoap ns1  service method-encoding:	generatePsamCardNo literal
//gsoap ns1  service method-action:	generatePsamCardNo ""
//gsoap ns1  service method-output-action:	generatePsamCardNo Response
int __ns1__generatePsamCardNo(
    ns1__generatePsamCardNo*            ns1__generatePsamCardNo_,	///< Input parameter
    ns1__generatePsamCardNoResponse*    ns1__generatePsamCardNoResponse_	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__storePsamCard                                                     *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__storePsamCard" of service binding "PrinterServiceServiceSoapBinding"

/**

Operation details:

  - SOAP document/literal style messaging

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__storePsamCard(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    ns1__storePsamCard*                 ns1__storePsamCard_,
    // output parameters:
    ns1__storePsamCardResponse*         ns1__storePsamCardResponse_
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__storePsamCard(
    struct soap *soap,
    // input parameters:
    ns1__storePsamCard*                 ns1__storePsamCard_,
    // output parameters:
    ns1__storePsamCardResponse*         ns1__storePsamCardResponse_
  );
@endcode

C++ proxy class (defined in soapPrinterServiceServiceSoapBindingProxy.h):
@code
  class PrinterServiceServiceSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapPrinterServiceServiceSoapBindingService.h):
@code
  class PrinterServiceServiceSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	storePsamCard SOAP
//gsoap ns1  service method-style:	storePsamCard document
//gsoap ns1  service method-encoding:	storePsamCard literal
//gsoap ns1  service method-action:	storePsamCard ""
//gsoap ns1  service method-output-action:	storePsamCard Response
int __ns1__storePsamCard(
    ns1__storePsamCard*                 ns1__storePsamCard_,	///< Input parameter
    ns1__storePsamCardResponse*         ns1__storePsamCardResponse_	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__generatePassword                                                  *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__generatePassword" of service binding "PrinterServiceServiceSoapBinding"

/**

Operation details:

  - SOAP document/literal style messaging

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__generatePassword(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    ns1__generatePassword*              ns1__generatePassword_,
    // output parameters:
    ns1__generatePasswordResponse*      ns1__generatePasswordResponse_
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__generatePassword(
    struct soap *soap,
    // input parameters:
    ns1__generatePassword*              ns1__generatePassword_,
    // output parameters:
    ns1__generatePasswordResponse*      ns1__generatePasswordResponse_
  );
@endcode

C++ proxy class (defined in soapPrinterServiceServiceSoapBindingProxy.h):
@code
  class PrinterServiceServiceSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapPrinterServiceServiceSoapBindingService.h):
@code
  class PrinterServiceServiceSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	generatePassword SOAP
//gsoap ns1  service method-style:	generatePassword document
//gsoap ns1  service method-encoding:	generatePassword literal
//gsoap ns1  service method-action:	generatePassword ""
//gsoap ns1  service method-output-action:	generatePassword Response
int __ns1__generatePassword(
    ns1__generatePassword*              ns1__generatePassword_,	///< Input parameter
    ns1__generatePasswordResponse*      ns1__generatePasswordResponse_	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__storeCard                                                         *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__storeCard" of service binding "PrinterServiceServiceSoapBinding"

/**

Operation details:

  - SOAP document/literal style messaging

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__storeCard(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    ns1__storeCard*                     ns1__storeCard_,
    // output parameters:
    ns1__storeCardResponse*             ns1__storeCardResponse_
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__storeCard(
    struct soap *soap,
    // input parameters:
    ns1__storeCard*                     ns1__storeCard_,
    // output parameters:
    ns1__storeCardResponse*             ns1__storeCardResponse_
  );
@endcode

C++ proxy class (defined in soapPrinterServiceServiceSoapBindingProxy.h):
@code
  class PrinterServiceServiceSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapPrinterServiceServiceSoapBindingService.h):
@code
  class PrinterServiceServiceSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	storeCard SOAP
//gsoap ns1  service method-style:	storeCard document
//gsoap ns1  service method-encoding:	storeCard literal
//gsoap ns1  service method-action:	storeCard ""
//gsoap ns1  service method-output-action:	storeCard Response
int __ns1__storeCard(
    ns1__storeCard*                     ns1__storeCard_,	///< Input parameter
    ns1__storeCardResponse*             ns1__storeCardResponse_	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__getCardTypeRules                                                  *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__getCardTypeRules" of service binding "PrinterServiceServiceSoapBinding"

/**

Operation details:

  - SOAP document/literal style messaging

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__getCardTypeRules(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    ns1__getCardTypeRules*              ns1__getCardTypeRules_,
    // output parameters:
    ns1__getCardTypeRulesResponse*      ns1__getCardTypeRulesResponse_
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__getCardTypeRules(
    struct soap *soap,
    // input parameters:
    ns1__getCardTypeRules*              ns1__getCardTypeRules_,
    // output parameters:
    ns1__getCardTypeRulesResponse*      ns1__getCardTypeRulesResponse_
  );
@endcode

C++ proxy class (defined in soapPrinterServiceServiceSoapBindingProxy.h):
@code
  class PrinterServiceServiceSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapPrinterServiceServiceSoapBindingService.h):
@code
  class PrinterServiceServiceSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	getCardTypeRules SOAP
//gsoap ns1  service method-style:	getCardTypeRules document
//gsoap ns1  service method-encoding:	getCardTypeRules literal
//gsoap ns1  service method-action:	getCardTypeRules ""
//gsoap ns1  service method-output-action:	getCardTypeRules Response
int __ns1__getCardTypeRules(
    ns1__getCardTypeRules*              ns1__getCardTypeRules_,	///< Input parameter
    ns1__getCardTypeRulesResponse*      ns1__getCardTypeRulesResponse_	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__getMainKey                                                        *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__getMainKey" of service binding "PrinterServiceServiceSoapBinding"

/**

Operation details:

  - SOAP document/literal style messaging

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__getMainKey(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    ns1__getMainKey*                    ns1__getMainKey_,
    // output parameters:
    ns1__getMainKeyResponse*            ns1__getMainKeyResponse_
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__getMainKey(
    struct soap *soap,
    // input parameters:
    ns1__getMainKey*                    ns1__getMainKey_,
    // output parameters:
    ns1__getMainKeyResponse*            ns1__getMainKeyResponse_
  );
@endcode

C++ proxy class (defined in soapPrinterServiceServiceSoapBindingProxy.h):
@code
  class PrinterServiceServiceSoapBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapPrinterServiceServiceSoapBindingService.h):
@code
  class PrinterServiceServiceSoapBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	getMainKey SOAP
//gsoap ns1  service method-style:	getMainKey document
//gsoap ns1  service method-encoding:	getMainKey literal
//gsoap ns1  service method-action:	getMainKey ""
//gsoap ns1  service method-output-action:	getMainKey Response
int __ns1__getMainKey(
    ns1__getMainKey*                    ns1__getMainKey_,	///< Input parameter
    ns1__getMainKeyResponse*            ns1__getMainKeyResponse_	///< Output parameter
);

/**

@page PrinterServiceServiceSoapBinding Binding "PrinterServiceServiceSoapBinding"

@section PrinterServiceServiceSoapBinding_policy_enablers Policy Enablers of Binding  "PrinterServiceServiceSoapBinding"

Based on policies, this service imports

  - WS-Policy reminders and enablers:
    - WS-Addressing 1.0 (2005/08, accepts 2004/08):
	@code
	#import "wsa5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-Addressing (2004/08):
	@code
	#import "wsa.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-ReliableMessaging 1.0:
	@code
	#import "wsrm5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-ReliableMessaging 1.1:
	@code
	#import "wsrm.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.0 (accepts 1.1):
	@code
	#import "wsse.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.1 (accepts 1.0):
	@code
	#import "wsse11.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - HTTP Digest Authentication:
	@code
	#include "plugin/httpda.h"
	soap_register_plugin(soap, soap_http_da); // register the HTTP DA plugin in your code
	// See the user guide gsoap/doc/httpda/html/index.html
	@endcode
*/


/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

Data can be read in XML and deserialized from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

Data can be serialized in XML and written to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback

The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


@section ns1 Top-level root elements of schema "http://service.ws.redcard.com/"

  - <ns1:generatePassword> (use wsdl2h option -g to auto-generate)

  - <ns1:generatePasswordResponse> (use wsdl2h option -g to auto-generate)

  - <ns1:generatePsamCardNo> (use wsdl2h option -g to auto-generate)

  - <ns1:generatePsamCardNoResponse> (use wsdl2h option -g to auto-generate)

  - <ns1:getCardTypeRules> (use wsdl2h option -g to auto-generate)

  - <ns1:getCardTypeRulesResponse> (use wsdl2h option -g to auto-generate)

  - <ns1:getMainKey> (use wsdl2h option -g to auto-generate)

  - <ns1:getMainKeyResponse> (use wsdl2h option -g to auto-generate)

  - <ns1:storeCard> (use wsdl2h option -g to auto-generate)

  - <ns1:storeCardResponse> (use wsdl2h option -g to auto-generate)

  - <ns1:storePsamCard> (use wsdl2h option -g to auto-generate)

  - <ns1:storePsamCardResponse> (use wsdl2h option -g to auto-generate)

  - <ns1:verifyUser> (use wsdl2h option -g to auto-generate)

  - <ns1:verifyUserResponse> (use wsdl2h option -g to auto-generate)

*/

/* End of wpsoap.h */
